### ISSUE TITLE
HPatchLite工程中的一些目录是空的，导致无法编译。

### ISSUE THREAD

**Issue by miracleyfm** [sisong/HPatchLite#11]
$ cd <dir>
$ git clone --recursive https://github.com/sisong/HPatchLite.git
用 [Visual Studio](https://visualstudio.microsoft.com/) 打开 HPatchLite/builds/vc/HPatchLite.sln 编译

但是，当打开HPatchLite.sln，出现如下错误提示等：
 
   错误	C1083	无法打开源文件: “..\..\HDiffPatch\libParallel\parallel_import.cpp”: No such file or directory		 

实际上，HDiffPatch是个空目录。

使用其它方式下载工程文件，同样存在如上错误提示。

**Comment by sisong** [comment]
是因为子仓库没有下载下来 ,重新下载：  
```
$ cd <HPatchLite源代码路径>   
$ git submodule update --init --recursive
```

**Comment by miracleyfm** [comment]
Thank you very much!
