### ISSUE TITLE
 打补丁 库api 接口如何在没有fopen/fread调用的单片机上使用？

### ISSUE THREAD

**Issue by miracleyfm** [sisong/HPatchLite#12]
打补丁使用的库api 接口 hpatch_lite_open/hpi_BOOL hpatch_lite_patch，需要调用fopen/fread操作。但是不少单片机裸机系统上不支持fopen/fread，所以就不能使用当前现有的库接口来在单片即上实现patch功能。
     如果能提供不依赖fopen/fread的API接口，比如当这些API patch接口的入参数据已经是读取文件之后的数据，库接口就更具有通用性，就方便在单片机上进行移植调用了。

**Comment by sisong** [comment]
现在的api和文件系统无关啊
单片机上已经跑过这个代码了

**Comment by miracleyfm** [comment]
单片机上使用hpatch_lite_patch是可以的。但是hpatch_lite_open包含fopen/fread函数的调用，而这些函数在我的单片机系统上是不被支持的。

**Comment by sisong** [comment]
你再仔细看看hpatch_lite_open的代码

**Comment by miracleyfm** [comment]
好的，非常感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sisong/HPatchLite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sisong/HPatchLite]  打补丁 库api 接口如何在没有fopen/fread调用的单片机上使用？ (Issue #12)





 
你再仔细看看hpatch_lite_open的代码

**Comment by miracleyfm** [comment]
我再次仔细看了hpatch_lite_open代码，有如下理解：
（1）hpatch_lite_open的入参“diff_data”是函数hpatchi在调用hpatch_lite_open之前，通过使用_wfopen_s操作获得的补丁文件指针（为“File *：类型）。
（2）hpatch_lite_open函数针对入参diff_data进一步进行了操作： 调用了 _do_readFile，该函数又进一步调用fread函数，对文件指针diff_data指向的文件进行读数据操作。
   所以我的理解是：由于我的单片机系统不支持标准c库函数fread，所以我得自己另外编写函数代替hpatch_lite_open功能，而不能直接使用API函数hpatch_lite_open，接下来我就可以直接使用API函数hpatch_lite_patch了。我的这个理解对吧？

  十分感谢前辈的指导！

**Comment by sisong** [comment]
不是   
hpatch_lite_open跟文件系统没有关系。   它是通过你提供的参数来间接操作补丁数据的，它不知道补丁的存储形式。
