### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by someburner** [sisong/HPatchLite#15]
On some systems, e.g. FreeRTOS, it is advised to not spend too long in a loop without occasionally yielding for other tasks to run. It would be nice to have some sort of progress indicator or optional callback stub to allow the user to yield during long loops. You could use the read/write stubs to see progress but it seems that execution time varies a lot between each `coverCount`. This might be more specific to `tuz` than hdiffpatch though.

**Comment by sisong** [comment]
The recommended solution now: update patch progress  indicator(writeNewPos/NewSize) in `hpatchi_listener_t.write_new` callback function, and allow switch task or thread yield.
