### ISSUE TITLE
如何使用库API函数呢？

### ISSUE THREAD

**Issue by lss157** [sisong/HPatchLite#16]

**Comment by lss157** [comment]
![1692002020440](https://github.com/sisong/HPatchLite/assets/49358108/adc115e0-17d7-46db-8372-ac6de0c8fcc9)
若想使用这两个库API函数并且调用压缩函数，需要包含什么文件夹进自己的项目呢？

**Comment by sisong** [comment]
HPatchLite库默认支持3种压缩库：tinyuz、zlib、lzma   
建议根据你的需要选择其中一种 ，另外也支持用插件的方式自己添加其他压缩算法； 这种方式下，就是边解压边patch。   
当然也可以选择不压缩补丁，传输补丁数据时自己处理压缩和解压；这种方式下，就只需要patch。   
   
关于diff部分，可以使用我编译好的release中的hdiffi命令行程序来创建补丁就行；    
patch部分，只需要包含 HPatchLite\HDiffPatch\libHDiffPatch\HPatchLite 目录下的代码；    
解压缩的话，根据自己选择的压缩算法来决定需要用到哪些代码，比如 如果选择了tinyuz压缩算法，那需要包含 HPatchLite/tinyuz/decompress 目录下的代码；   
   

关于如何使用patch函数，可以参考 HPatchLite/hpatchi.c 中的hpatchi函数

**Comment by lss157** [comment]
![1700738468279](https://github.com/sisong/HPatchLite/assets/49358108/9b98de8d-2f45-4ce5-bd83-c59d472dae12)
在项目里放了以上所说的文件，可是还是不太懂如何使用patch函数，如果是直接放到Flash中，是否要重新写读取函数？

**Comment by sisong** [comment]
主要流程就是依次调用hpatch_lite.h中的  hpatch_lite_open 和 hpatch_lite_patch 这两个函数完成patch任务；
需要自己整理好调用参数需要的结构和其回调函数(读取old和补丁，写入new)，可以借鉴 hpatchi.c文件中的 hpatchi 演示函数。

**Comment by lss157** [comment]
![8Y07)Q454`S7~CC3`E6C(6F](https://github.com/sisong/HPatchLite/assets/49358108/75b6b5b7-b017-4b9f-bb81-e5101bb2718c)
不太理解这个HPatchLite的Listener，前面的hpatch_lite_open不是已经读取过差分文件了吗，但是 hpatch_lite_patch 函数的Listener两个参数都是关于差分文件，反而原始文件不知道怎么读取了？

**Comment by lss157** [comment]
![2LPC)3B_X_~ZD`001673T4](https://github.com/sisong/HPatchLite/assets/49358108/6dc5b1ce-dde1-4ce5-9222-ac1f5804574e)
是不是还要在Listener外层再封装一层自己的Listener？

**Comment by sisong** [comment]
hpatch_lite_open 并不保存补丁数据的读取方式，所以hpatch_lite_patch的参数中还需要传。   
hpatchlite_listener_t外不必须封装，填好监听的参数就行

**Comment by lss157** [comment]
我将原始用户程序代码放在FLASH一个位置A_ADDR，差分文件放在Flash另一个位置B_ADDR，进行解压缩解差分时，可以直接将新生成的程序覆盖到差分文件B_ADDR位置上吗？还是新生成的程序需要重新找一个位置存放，比如说C_ADDR？
想知道可以一边生成新程序一边覆盖差分程序吗？

**Comment by sisong** [comment]
本库暂时还不支持原地更新；另外以后也不会支持覆盖掉补丁；所以当前只能另找位置放置。   如果想节省掉补丁文件占用的磁盘，可以考虑启动patch后，再在回调函数中按需依次下载补丁数据。

**Comment by lss157** [comment]
![08O29O9N%S))(%_59EN94V](https://github.com/sisong/HPatchLite/assets/49358108/aab21771-3cc0-4c0f-8819-3b3788947cc9)
其中的out_newSize和out_uncompressSize分别指什么呢？

**Comment by lss157** [comment]
![B7~O X1$~P6E1 N8B_%JG}2](https://github.com/sisong/HPatchLite/assets/49358108/490fc147-90a3-4b43-adee-e1578910c9f5)
如果我想，把得到的新数据写入到新地址上去，是不是需要改动源码呢？因为源码好像是得到新数据后直接写回原地址处了。
还是不太懂这个函数该如何实现，因为传入的参数只有listener、data、data_size，只知道一个差分数据的地址，但是原数据的地址和新数据的地址都没有传进来。

**Comment by sisong** [comment]
patch过程中的3个文件的数据，都是通过回调函数读写的。 提供给patch函数的内存只用作缓存。

**Comment by sisong** [comment]
新版本HPatchLite添加了简单的原地更新实现，见readme说明文档。  另外，文档也增加了移植的说明。
