### ISSUE TITLE
能否提供一下单片机的移植教程

### ISSUE THREAD

**Issue by fanleung** [sisong/HPatchLite#17]
作者你好，已经使用编译好的命令行程序，用 hdiffi 和 tinyuz 命令行输出 diff 固件了。
现在卡在使用 api 调用 patch，看了 issues 的一些回复，移植起来还是有点吃力

**Comment by sisong** [comment]
借鉴 hpatchi 程序代码，最好能单步跟踪看看。   
拷贝  HDiffPatch\libHDiffPatch\HPatchLite 和 tinyuz\decompress 2个目录，   
主要是调用 hpatch_lite_open 和 hpatch_lite_patch，处理好 hpatchi_listener_t 这个结构（这个比较简单）；    
因为使用了压缩，所以需要桥接一下解压函数，可以借鉴 hpatchi_patch 函数处理好 hpatchi_listener_t 的数据。
