### ISSUE TITLE
询问一个程序错误的问题

### ISSUE THREAD

**Issue by wkkkk1** [sisong/HPatchLite#18]
您好，在使用Hpatchlite中遇到一个这样的问题：
       环境，一块linux开发板 。 使用system(" hpatchi  xx  yy zz ")，可以成功生成有用 的补丁，手敲命令也可以。    然而在某个程序中，增加这行代码的时候，system的返回值直接打印是1500.     并且hpatch_lite_patch() run ERROR!
hpatchi_patch() run ERROR!   有这样的报错，请问这个可能是什么方面的问题呀

**Comment by sisong** [comment]
我对linux系统的system函数不熟悉，1500返回值不知道是什么意思，这不是hpatchlite命令行定义的返回值。     
可以试试在出错的系统上，直接使用相同的参数运行hpatchi看看情况。   
“hpatchi_patch() run ERROR! 有这样的报错”  这说明patch执行过程中一定检测到了一个错误，请检查返回值看看原因

**Comment by sisong** [comment]
（猜测）因为1500返回值的高字节值为5，即这对应hpatchi的错误码5，表示文件数据读取失败。

**Comment by wkkkk1** [comment]
谢谢您的回复，请问您那边的错误值21是代表什么。

**Comment by sisong** [comment]
你可以自己参考 THPatchiResult 的定义；   
21 对应 HPATCHI_PATCH_ERROR ，patch时报错，没有发现具体原因，那猜测可能是补丁数据错误。

**Comment by wkkkk1** [comment]
我在同样的软硬件环境，单独使用system写程序编译执行或者敲命令行，是可以正常运行得到预期结果。然而把它加到一个工程里去，就在那个地方报错。该工程开始的功能就是，作为一个协议的服务器，接受补丁，然后system调用hpatchi命令行得到新的包，在这个地方报错，生成得到一个错误包。而这个位置system调用比如md5sum，bash命令都没问题。                                                 
       程序结束后，查看接收的补丁与之前生成的补丁的md5sum值一致。很奇怪，这会是补丁数据错误吗？

**Comment by sisong** [comment]
看描述是比较奇怪的bug状况。     
是否是内存资源不足? 或者内存数据被非法写入?    

可以打印看看调用参数是否正常？     
建议可以用二分法，不断的缩减项目功能模块看看。   
或者研究一下system的返回值；或将其替换为popen函数试试。

**Comment by wkkkk1** [comment]
谢谢回复，我这边解决了，确实是数据问题，那个补丁文件没close(fd)。
